apiVersion: v1
kind: Service
metadata:
  name: amf-namf
  namespace: open5gs-core
  labels:
    app: open5gs
    nf: amf
spec:
  selector:
    app: open5gs
    nf: amf
  ports:
    - name: sbi
      port: 7777
      targetPort: 7777
    - name: ngap
      port: 38412
      protocol: SCTP
      targetPort: 38412
