apiVersion: v1
kind: Pod
metadata:
  name: pfcp-attacker
  namespace: open5gs-edge
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        { "name": "n4network", "interface": "n4", "ips": ["10.10.4.250/24"] },
        { "name": "n3network", "interface": "n3", "ips": ["10.10.3.250/24"] }
      ]
spec:
  nodeName: worker-open5gs-02
  containers:
  - name: attacker
    image: python:3.11
    command: ["sleep", "infinity"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "NET_RAW"]
  restartPolicy: Never
