# =============================================================================
# Scénario FL — Edge2 (UPF3/SMF3)
# Attaques : pfcp_flood (commun), pfcp_session_mod,
#            udp_flood_high, udp_flood_max
# Bénin : normal, ue_http_intensive
# Durée : 40 minutes
# =============================================================================

0 5 normal

5 7 pfcp_flood
7 10 normal

10 12 pfcp_session_mod
12 15 normal
15 17 udp_flood_high
17 19 udp_flood_max
19 22 normal
22 24 ue_http_intensive
24 27 normal

27 40 normal
