# =============================================================================
# Scénario FL — Edge1 (UPF2/SMF2)
# Attaques : pfcp_flood (commun), pfcp_session_del, gtp_flood,
#            udp_flood_low, udp_flood_medium
# Bénin : normal, ue_http_intensive
# Durée : 40 minutes
# =============================================================================

0 5 normal

5 7 pfcp_flood
7 10 normal

10 12 pfcp_session_del
12 15 normal
15 17 gtp_flood
17 20 normal
20 22 udp_flood_low
22 24 udp_flood_medium
24 26 normal
26 28 ue_http_intensive
28 31 normal

31 40 normal
