logger:
  file:
    path: /opt/open5gs/var/log/open5gs/nrf.log

nrf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
        advertise: open5gs-core-nrf-sbi.open5gs-core.svc.cluster.local
