apiVersion: v1
kind: Service
metadata:
  name: smf2-nsmf
  namespace: open5gs-edge
  labels:
    app: open5gs
    nf: smf
    name: smf2
spec:
  selector:
    app: open5gs
    nf: smf
    name: smf2
  ports:
    - name: sbi
      port: 7777
      targetPort: 7777
    - name: pfcp
      port: 8805
      targetPort: 8805
      protocol: UDP
